[package]
name = "infc"
version = "0.1.0"
edition = "2021"

[dependencies]
tree-sitter = ">=0.22.6"
tree-sitter-inference = "0.0.28"
clap = { version = "4.5.15", features = ["derive"] }
walkdir = "2.5.0"
tempfile = "3"
infc_compiler = { path = "../infc_compiler" }