name: Build Release

on:
  release:
    types: [created]

jobs:
  build:
    name: Build and test infc
    strategy:
      matrix:
        os: [Linux, Windows]
        toolchain:
          - nightly
    runs-on: [self-hosted, X64, "${{ matrix.os }}"]
    steps:
      - name: Setup Rust
        uses: actions/checkout@v4.1.3
        with:
          lfs: true
      - name: Update Rust
        run: rustup update ${{ matrix.toolchain }}
          | rustup default ${{ matrix.toolchain }}
      - name: Install clippy nightly
        run: rustup component add clippy-preview
      - name: Install Cargo audit
        run: cargo install cargo-audit
      - name: Build
        run: cargo build --release --verbose
      - name: Test
        run: cargo test --verbose --lib
      - name: Clippy
        run: cargo clippy --verbose -- -D warnings
      - name: Audit
        run: cargo audit
      - name: Prepare Artifact Package (Windows)
        if: matrix.os == 'Windows'
        run: |
          New-Item -ItemType Directory -Force -Path artifact\bin
          New-Item -ItemType Directory -Force -Path artifact\lib
          Copy-Item target\release\infc.exe artifact\
          Copy-Item book\check_deps.ps1 artifact\
          Copy-Item target\release\bin\* artifact\bin\
          Copy-Item target\release\lib\* artifact\lib\
      - name: Prepare Artifact Package (Linux)
        if: matrix.os == 'Linux'
        run: |
          mkdir -p artifact/bin
          mkdir -p artifact/lib
          cp target/release/infc artifact/
          cp target/release/bin/* artifact/bin/
          cp target/release/lib/* artifact/lib/
      - name: Package Artifact (Windows)
        if: matrix.os == 'Windows'
        run: |
          7z a -tzip infc-${{ matrix.os }}-64.zip artifact .
          certutil -hashfile infc-${{ matrix.os }}-64.zip SHA256 > infc-${{ matrix.os }}-64.zip.sha256
      - name: Package Artifact (Linux)
        if: matrix.os == 'Linux'
        run: |
          tar -czf infc-${{ matrix.os }}-64.tar.gz -C artifact .
          sha256sum infc-${{ matrix.os }}-64.tar.gz > infc-${{ matrix.os }}-64.tar.gz.sha256
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: infc-${{ matrix.os }}-64
          path: |
            infc-${{ matrix.os }}-64.*
          retention-days: 90
          compression-level: 0
